name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      working-directory: Azure-Commitlog-Check
      
    - name: Build
      run: dotnet build --no-restore
      working-directory: Azure-Commitlog-Check
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: Azure-Commitlog-Check
      
    - name: Publish
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: dotnet publish -c Release -o publish
      working-directory: Azure-Commitlog-Check
      
    - name: Upload artifact
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: actions/upload-artifact@v4
      with:
        name: Azure-Commitlog-Check
        path: Azure-Commitlog-Check/publish/
