name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore "Azure-Commitlog-Check/Azure-Commitlog-Check.csproj"
      
    - name: Build
      run: dotnet build "Azure-Commitlog-Check/Azure-Commitlog-Check.csproj" --configuration Release --no-restore
      
    - name: Test
      run: |
        if (Test-Path -Path "Azure-Commitlog-Check.Tests") {
          dotnet test "Azure-Commitlog-Check.Tests" --configuration Release --no-build --verbosity normal
        } else {
          Write-Host "No test project found, skipping tests"
        }
      shell: pwsh
